export { default as Home } from "./Home"
export { default as ArtistBio } from "./ArtistBio"
export { default as Contests } from "./Contests"
export { default as Works } from "./Works"
export { default as Services } from "./Services"
export { default as Contact } from "./Contact"